name: CI on Push and Pull Request

on: [push, pull_request]

jobs:
  Practice:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: ls
    - name: Run a multi-line script
      run: |
        cd InstagramMessages.sln
        ls
    - name: Show what in there
      run: |
        ls
    - name: Show what is inside
      run: |
        cd ..
        ls
        
