name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Build App
  build:
    runs-on: windows-latest
    
    env:
      SERVICE_APP_KEY: ${{ secrets.SERVICE_APP_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.0        

      - name: Build Solution
        run: msbuild ./InstagramMessages.sln /restore /p:Configuration=Release

      - name: Create and Sign the APK
        run: msbuild InstagramMessages\InstagramMessages.Android\InstagramMessages.Android.csproj /t:SignAndroidPackage /p:Configuration=Release /p:OutputPath=bin\Release\

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: InstagramMessages.apk
          path: InstagramMessages\InstagramMessages.Android\bin\Release\com.companyname.myapplication-Signed.apk 
